# Generated by Django 3.1.2 on 2020-11-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutchmanserve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=400)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='interests',
            field=models.CharField(choices=[('ST', 'Service Trips'), ('Food', 'Food'), ('Hou', 'Housing'), ('Edu', 'Education'), ('Envir', 'Environment'), ('Ani', 'Animals'), ('HandW', 'Health & Wellness'), ('OA', 'Older Adults'), ('Dis', 'Disabilities'), ('Vet', 'Veterans')], default='ST', max_length=5),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Lebanon Valley College', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=45),
        ),
    ]
