# Generated by Django 3.1.2 on 2020-11-26 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dutchmanserve', '0002_auto_20201119_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='pub_date',
            new_name='date',
        ),
    ]
