# Generated by Django 3.1.2 on 2020-11-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutchmanserve', '0003_auto_20201125_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_description',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='imagepath',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='Lebanon Valley College', max_length=50, null=True),
        ),
    ]
