# Generated by Django 3.1.2 on 2020-11-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutchmanserve', '0004_auto_20201125_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='registered',
            field=models.ManyToManyField(to='dutchmanserve.User'),
        ),
    ]
