# Generated by Django 3.1.2 on 2020-11-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutchmanserve', '0006_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='interests',
        ),
        migrations.AddField(
            model_name='event',
            name='interests',
            field=models.ManyToManyField(to='dutchmanserve.Interests'),
        ),
    ]
