# Generated by Django 3.1.2 on 2020-11-27 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dutchmanserve', '0007_auto_20201126_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='eventName',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='org_name',
            new_name='orgName',
        ),
        migrations.AddField(
            model_name='organization',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='imagepath',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='officers',
            field=models.ManyToManyField(related_name='Officers', to='dutchmanserve.User'),
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(related_name='members', to='dutchmanserve.User'),
        ),
        migrations.AddField(
            model_name='report',
            name='additional',
            field=models.ManyToManyField(related_name='People', to='dutchmanserve.User'),
        ),
        migrations.AddField(
            model_name='report',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dutchmanserve.event'),
        ),
        migrations.AddField(
            model_name='report',
            name='imagepath',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dutchmanserve.user'),
        ),
        migrations.AlterField(
            model_name='report',
            name='hours',
            field=models.IntegerField(),
        ),
    ]
