# Generated by Django 3.1.2 on 2020-11-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutchmanserve', '0010_auto_20201127_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registered',
            field=models.ManyToManyField(null=True, to='dutchmanserve.User'),
        ),
    ]
