# Generated by Django 3.1.2 on 2020-11-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutchmanserve', '0012_auto_20201128_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventName',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, to='dutchmanserve.Interests'),
        ),
    ]
