# Generated by Django 3.1.2 on 2020-11-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutchmanserve', '0013_auto_20201128_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='officers',
            field=models.ManyToManyField(blank=True, null=True, related_name='Officers', to='dutchmanserve.User'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='orgName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='dutchmanserve.User'),
        ),
    ]
