# Generated by Django 3.1.2 on 2020-11-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutchmanserve', '0017_auto_20201128_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
