# Generated by Django 3.1.2 on 2020-11-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutchmanserve', '0018_auto_20201128_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='additional',
            field=models.ManyToManyField(blank=True, related_name='People', to='dutchmanserve.User'),
        ),
        migrations.AlterField(
            model_name='report',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='imagepath',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
