# Generated by Django 3.1.2 on 2021-03-11 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('date', models.DateTimeField(null=True, verbose_name='Date')),
                ('location', models.CharField(default='Lebanon Valley College', max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('isCommunity', models.BooleanField()),
                ('isResidential', models.BooleanField()),
                ('isOngoing', models.BooleanField()),
                ('imagepath', models.FileField(blank=True, null=True, upload_to='')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('imagepath', models.FileField(blank=True, null=True, upload_to='')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('emailAddress', models.EmailField(max_length=100)),
                ('events', models.ManyToManyField(blank=True, related_name='events', to='dutchmenserve.Event')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites', to='dutchmenserve.Event')),
                ('interests', models.ManyToManyField(blank=True, to='dutchmenserve.Interest')),
                ('organizations', models.ManyToManyField(blank=True, to='dutchmenserve.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagepath', models.FileField(blank=True, null=True, upload_to='')),
                ('deleted', models.BooleanField(default=False)),
                ('additional', models.ManyToManyField(blank=True, to='dutchmenserve.User')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eid', to='dutchmenserve.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uid', to='dutchmenserve.user')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='officers',
            field=models.ManyToManyField(blank=True, to='dutchmenserve.User'),
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='members', to='dutchmenserve.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='interests',
            field=models.ManyToManyField(blank=True, to='dutchmenserve.Interest'),
        ),
        migrations.AddField(
            model_name='event',
            name='registered',
            field=models.ManyToManyField(blank=True, to='dutchmenserve.User'),
        ),
    ]
