# Generated by Django 3.2.9 on 2021-12-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutchmenserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csprojects11112021',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csprojects11112021',
            name='eventdate',
            field=models.DateTimeField(blank=True, db_column='eventDate', null=True),
        ),
    ]
