# Generated by Django 3.1.2 on 2021-05-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutchmenserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='color',
            field=models.CharField(default='#ffffff', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interest',
            name='fillColor',
            field=models.CharField(default='#ffffff', max_length=10),
            preserve_default=False,
        ),
    ]
