# Generated by Django 3.1.2 on 2021-03-15 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dutchmenserve', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='interests',
        ),
        migrations.AddField(
            model_name='event',
            name='interests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dutchmenserve.interest'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='registered',
        ),
        migrations.AddField(
            model_name='event',
            name='registered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dutchmenserve.user'),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='officers',
        ),
        migrations.AddField(
            model_name='organization',
            name='officers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dutchmenserve.user'),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='users',
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='dutchmenserve.user'),
        ),
        migrations.RemoveField(
            model_name='report',
            name='additional',
        ),
        migrations.AddField(
            model_name='report',
            name='additional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dutchmenserve.user'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='dutchmenserve.event'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites', to='dutchmenserve.event'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='interests',
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dutchmenserve.interest'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='organizations',
        ),
        migrations.AddField(
            model_name='user',
            name='organizations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dutchmenserve.organization'),
        ),
    ]
