# Generated by Django 3.1.2 on 2021-03-15 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dutchmenserve', '0002_auto_20210314_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='additional',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='event',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registered',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='officers',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organizations',
        ),
        migrations.CreateModel(
            name='UserInterested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dutchmenserve.interest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dutchmenserve.user')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dutchmenserve.event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dutchmenserve.user')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dutchmenserve.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dutchmenserve.user')),
            ],
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dutchmenserve.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dutchmenserve.user')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dutchmenserve.event')),
                ('interest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dutchmenserve.interest')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='officer',
            field=models.ManyToManyField(blank=True, related_name='officer', through='dutchmenserve.Leadership', to='dutchmenserve.Organization'),
        ),
        migrations.AddField(
            model_name='event',
            name='interests',
            field=models.ManyToManyField(blank=True, through='dutchmenserve.EventType', to='dutchmenserve.Interest'),
        ),
        migrations.AddField(
            model_name='event',
            name='registered',
            field=models.ManyToManyField(blank=True, through='dutchmenserve.Registration', to='dutchmenserve.User'),
        ),
        migrations.AddField(
            model_name='organization',
            name='officers',
            field=models.ManyToManyField(blank=True, through='dutchmenserve.Leadership', to='dutchmenserve.User'),
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='members', through='dutchmenserve.Membership', to='dutchmenserve.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(blank=True, through='dutchmenserve.Registration', to='dutchmenserve.Event'),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, through='dutchmenserve.UserInterested', to='dutchmenserve.Interest'),
        ),
        migrations.AddField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(blank=True, through='dutchmenserve.Membership', to='dutchmenserve.Organization'),
        ),
    ]
