# Generated by Django 3.2.8 on 2021-11-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutchmenserve', '0002_auto_20210508_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('cretaedDate', models.DateTimeField(null=True, verbose_name='Date')),
                ('reviewDate', models.DateTimeField(null=True, verbose_name='Date')),
                ('GroupType', models.CharField(max_length=25)),
                ('approved', models.CharField(max_length=20)),
                ('subGroup', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('approved', models.CharField(max_length=20)),
                ('cretaedDate', models.DateTimeField(null=True, verbose_name='Date')),
                ('reviewDate', models.DateTimeField(null=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='StudentReportingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectId', models.IntegerField()),
                ('groupId', models.IntegerField()),
                ('studentId', models.IntegerField()),
                ('hoursReported', models.DecimalField(decimal_places=2, max_digits=5)),
                ('serviceDate', models.DateTimeField(null=True, verbose_name='Date')),
                ('approved', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=500)),
                ('ResidentialStatusEligible', models.BooleanField()),
            ],
        ),
    ]
