# Generated by Django 3.1.2 on 2021-03-15 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dutchmenserve', '0003_auto_20210315_0002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventType',
            new_name='EventInterest',
        ),
        migrations.RenameModel(
            old_name='UserInterested',
            new_name='UserInterest',
        ),
    ]
