# Generated by Django 3.2.8 on 2021-11-11 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dutchmenserve', '0005_auto_20211111_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='GroupType',
            new_name='groupType',
        ),
        migrations.RenameField(
            model_name='studentreportinglog',
            old_name='ResidentialStatusEligible',
            new_name='residentialStatusEligible',
        ),
    ]
