# Generated by Django 3.2.8 on 2021-11-12 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dutchmenserve', '0006_auto_20211111_1833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='csGroups11112021',
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='csProjects11112021',
        ),
        migrations.RenameModel(
            old_name='StudentReportingLog',
            new_name='StudentReportingLog11112021',
        ),
    ]
